"""added days to hire

Revision ID: 48dfeaa46ba7
Revises: 991ecb2bf269
Create Date: 2025-04-19 10:18:40.069431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dfeaa46ba7'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('max', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Integer(), nullable=True),
    sa.Column('num_of_postings', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('standard_job_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'standard_job_id', name='unique_country_code_standard_job_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire_stats', schema='public')
    # ### end Alembic commands ###
