"""

Revision ID: cae192c27046
Revises: 48dfeaa46ba7
Create Date: 2025-04-20 22:50:49.125046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae192c27046'
down_revision = '48dfeaa46ba7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('days_to_hire_stats', sa.Column('calculated_at', sa.String(), nullable=True))
    op.drop_constraint('unique_country_code_standard_job_id', 'days_to_hire_stats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_country_code_standard_job_id', 'days_to_hire_stats', ['country_code', 'standard_job_id'])
    op.drop_column('days_to_hire_stats', 'calculated_at')
    # ### end Alembic commands ###
